--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-09-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ATTACHMENT_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CLEVERNOTEADMIN"."ATTACHMENT_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOARD_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CLEVERNOTEADMIN"."BOARD_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BOARD_TYPE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CLEVERNOTEADMIN"."BOARD_TYPE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CATEGORY_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CLEVERNOTEADMIN"."CATEGORY_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999 INCREMENT BY 1 START WITH 501 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NOTE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CLEVERNOTEADMIN"."NOTE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999 INCREMENT BY 1 START WITH 1041 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TAGGING_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CLEVERNOTEADMIN"."TAGGING_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TAG_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CLEVERNOTEADMIN"."TAG_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 401 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "CLEVERNOTEADMIN"."USER_SEQUENCE"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 398 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table APP_USER
--------------------------------------------------------

  CREATE TABLE "CLEVERNOTEADMIN"."APP_USER" 
   (	"EMAIL" VARCHAR2(50 BYTE), 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6), 
	"USERNAME" VARCHAR2(128 BYTE), 
	"PWHASH" VARCHAR2(256 BYTE), 
	"USER_NUM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CLEVERNOTEADMIN"."APP_USER"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."APP_USER"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."APP_USER"."UPDATED_AT" IS '수정일시';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."APP_USER"."USERNAME" IS '이름';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."APP_USER"."PWHASH" IS '패스워드(해쉬값)';
--------------------------------------------------------
--  DDL for Table ATTACHMENT_FILE
--------------------------------------------------------

  CREATE TABLE "CLEVERNOTEADMIN"."ATTACHMENT_FILE" 
   (	"ATTACHMENT_NUM" NUMBER(10,0), 
	"BOARD_NUM" NUMBER(10,0), 
	"NAME" VARCHAR2(1024 BYTE), 
	"FILE_SIZE" NUMBER(20,0), 
	"DATA" BLOB, 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6), 
	"MIMETYPE" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "CLEVERNOTEADMIN"."ATTACHMENT_FILE"."ATTACHMENT_NUM" IS '첨부파일번호';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."ATTACHMENT_FILE"."BOARD_NUM" IS '게시글 번호';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."ATTACHMENT_FILE"."NAME" IS '파일명';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."ATTACHMENT_FILE"."FILE_SIZE" IS '파일 크기';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."ATTACHMENT_FILE"."DATA" IS '데이터';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."ATTACHMENT_FILE"."CREATED_AT" IS '생성 일시';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."ATTACHMENT_FILE"."UPDATED_AT" IS '수정 일시';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."ATTACHMENT_FILE"."MIMETYPE" IS '파일 타입';
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "CLEVERNOTEADMIN"."BOARD" 
   (	"BOARD_NUM" NUMBER(10,0), 
	"TITLE" VARCHAR2(1024 BYTE), 
	"TYPE_NUM" NUMBER(10,0), 
	"USER_NUM" NUMBER(10,0), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp, 
	"HIT" NUMBER(10,0) DEFAULT 0, 
	"BOARD_GROUP" NUMBER(10,0) DEFAULT 0, 
	"STEP" NUMBER(10,0) DEFAULT 0, 
	"INDENT" NUMBER(10,0) DEFAULT 0, 
	"CONTENT" CLOB DEFAULT NULL, 
	"USERNAME" VARCHAR2(128 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD"."BOARD_NUM" IS '게시글 번호';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD"."TITLE" IS '게시글 제목';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD"."TYPE_NUM" IS '게시글 타입번호';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD"."USER_NUM" IS '작성자 번호';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD"."CREATED_AT" IS '생성 일시';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD"."UPDATED_AT" IS '수정 일시';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD"."HIT" IS '조회수';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD"."BOARD_GROUP" IS '게시글 그룹';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD"."STEP" IS '게시글 단계';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD"."INDENT" IS '들여쓰기 깊이';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD"."CONTENT" IS '게시글 내용';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD"."USERNAME" IS '이름
';
--------------------------------------------------------
--  DDL for Table BOARD_TYPE
--------------------------------------------------------

  CREATE TABLE "CLEVERNOTEADMIN"."BOARD_TYPE" 
   (	"TYPE_NUM" NUMBER(10,0), 
	"NAME" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD_TYPE"."TYPE_NUM" IS '타입 번호';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."BOARD_TYPE"."NAME" IS '타입이름';
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "CLEVERNOTEADMIN"."CATEGORY" 
   (	"TITLE" VARCHAR2(128 BYTE), 
	"CATEGORY_NUM" NUMBER(*,0), 
	"OWNER_NUM" NUMBER(*,0), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CLEVERNOTEADMIN"."CATEGORY"."TITLE" IS '제목';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."CATEGORY"."CATEGORY_NUM" IS '카데고리번호';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."CATEGORY"."OWNER_NUM" IS '사용자번호';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."CATEGORY"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."CATEGORY"."UPDATED_AT" IS '수정일시';
--------------------------------------------------------
--  DDL for Table NOTE
--------------------------------------------------------

  CREATE TABLE "CLEVERNOTEADMIN"."NOTE" 
   (	"CREATED_AT" TIMESTAMP (6) DEFAULT systimestamp, 
	"TITLE" VARCHAR2(1024 BYTE) DEFAULT '제목없음', 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT systimestamp, 
	"CONTENT" NCLOB, 
	"NOTE_NUM" NUMBER(*,0), 
	"CATEGORY_NUM" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TAG
--------------------------------------------------------

  CREATE TABLE "CLEVERNOTEADMIN"."TAG" 
   (	"TAG_NUM" NUMBER(10,0), 
	"WORD" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CLEVERNOTEADMIN"."TAG"."TAG_NUM" IS '태그 번호';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."TAG"."WORD" IS '태그';
--------------------------------------------------------
--  DDL for Table TAGGING
--------------------------------------------------------

  CREATE TABLE "CLEVERNOTEADMIN"."TAGGING" 
   (	"TAG_NUM" NUMBER(10,0), 
	"NOTE_NUM" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CLEVERNOTEADMIN"."TAGGING"."TAG_NUM" IS '태그 번호';
   COMMENT ON COLUMN "CLEVERNOTEADMIN"."TAGGING"."NOTE_NUM" IS '노트 번호';
REM INSERTING into CLEVERNOTEADMIN.APP_USER
SET DEFINE OFF;
REM INSERTING into CLEVERNOTEADMIN.ATTACHMENT_FILE
SET DEFINE OFF;
REM INSERTING into CLEVERNOTEADMIN.BOARD
SET DEFINE OFF;
REM INSERTING into CLEVERNOTEADMIN.BOARD_TYPE
SET DEFINE OFF;
REM INSERTING into CLEVERNOTEADMIN.CATEGORY
SET DEFINE OFF;
REM INSERTING into CLEVERNOTEADMIN.NOTE
SET DEFINE OFF;
REM INSERTING into CLEVERNOTEADMIN.TAG
SET DEFINE OFF;
REM INSERTING into CLEVERNOTEADMIN.TAGGING
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLEVERNOTEADMIN"."CATEGORY_PK" ON "CLEVERNOTEADMIN"."CATEGORY" ("CATEGORY_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_USER_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLEVERNOTEADMIN"."UNIQUE_USER_EMAIL" ON "CLEVERNOTEADMIN"."APP_USER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TAG_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLEVERNOTEADMIN"."TAG_UK1" ON "CLEVERNOTEADMIN"."TAG" ("WORD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLEVERNOTEADMIN"."BOARD_PK" ON "CLEVERNOTEADMIN"."BOARD" ("BOARD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BOARD_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLEVERNOTEADMIN"."BOARD_TYPE_PK" ON "CLEVERNOTEADMIN"."BOARD_TYPE" ("TYPE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NOTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLEVERNOTEADMIN"."NOTE_PK" ON "CLEVERNOTEADMIN"."NOTE" ("NOTE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ATTACHMENT_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLEVERNOTEADMIN"."ATTACHMENT_FILE_PK" ON "CLEVERNOTEADMIN"."ATTACHMENT_FILE" ("ATTACHMENT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TAGGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLEVERNOTEADMIN"."TAGGIN_PK" ON "CLEVERNOTEADMIN"."TAGGING" ("TAG_NUM", "NOTE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLEVERNOTEADMIN"."TAG_PK" ON "CLEVERNOTEADMIN"."TAG" ("TAG_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index APP_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLEVERNOTEADMIN"."APP_USER_PK" ON "CLEVERNOTEADMIN"."APP_USER" ("USER_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_FOR_DEFAULT_CATEGORY
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CLEVERNOTEADMIN"."TRIGGER_FOR_DEFAULT_CATEGORY" 
AFTER INSERT ON APP_USER FOR EACH ROW
BEGIN
    INSERT INTO Category (owner_num,category_num,title) 
    values ( :NEW.user_num, CATEGORY_SEQUENCE.nextval, 'None title');
END;
/
ALTER TRIGGER "CLEVERNOTEADMIN"."TRIGGER_FOR_DEFAULT_CATEGORY" ENABLE;
--------------------------------------------------------
--  Constraints for Table TAG
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."TAG" ADD CONSTRAINT "TAG_UK1" UNIQUE ("WORD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLEVERNOTEADMIN"."TAG" ADD CONSTRAINT "TAG_PK" PRIMARY KEY ("TAG_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLEVERNOTEADMIN"."TAG" MODIFY ("WORD" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."TAG" MODIFY ("TAG_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."CATEGORY" MODIFY ("UPDATED_AT" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."CATEGORY" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CATEGORY_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLEVERNOTEADMIN"."CATEGORY" MODIFY ("CATEGORY_NUM" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."CATEGORY" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_TYPE
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."BOARD_TYPE" ADD CONSTRAINT "BOARD_TYPE_PK" PRIMARY KEY ("TYPE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD_TYPE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD_TYPE" MODIFY ("TYPE_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAGGING
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."TAGGING" MODIFY ("NOTE_NUM" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."TAGGING" ADD CONSTRAINT "TAGGIN_PK" PRIMARY KEY ("TAG_NUM", "NOTE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLEVERNOTEADMIN"."TAGGING" MODIFY ("TAG_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("BOARD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" MODIFY ("INDENT" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" MODIFY ("STEP" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" MODIFY ("BOARD_GROUP" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" MODIFY ("HIT" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" MODIFY ("USER_NUM" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" MODIFY ("TYPE_NUM" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" MODIFY ("BOARD_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APP_USER
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."APP_USER" ADD CONSTRAINT "UNIQUE_USER_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLEVERNOTEADMIN"."APP_USER" ADD CONSTRAINT "APP_USER_PK" PRIMARY KEY ("USER_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLEVERNOTEADMIN"."APP_USER" MODIFY ("USER_NUM" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."APP_USER" MODIFY ("PWHASH" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."APP_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."APP_USER" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATTACHMENT_FILE
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."ATTACHMENT_FILE" MODIFY ("MIMETYPE" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."ATTACHMENT_FILE" ADD CONSTRAINT "ATTACHMENT_FILE_PK" PRIMARY KEY ("ATTACHMENT_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLEVERNOTEADMIN"."ATTACHMENT_FILE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."ATTACHMENT_FILE" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."ATTACHMENT_FILE" MODIFY ("FILE_SIZE" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."ATTACHMENT_FILE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."ATTACHMENT_FILE" MODIFY ("ATTACHMENT_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTE
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."NOTE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."NOTE" ADD CONSTRAINT "NOTE_PK" PRIMARY KEY ("NOTE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CLEVERNOTEADMIN"."NOTE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "CLEVERNOTEADMIN"."NOTE" MODIFY ("NOTE_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATTACHMENT_FILE
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."ATTACHMENT_FILE" ADD CONSTRAINT "ATTACHMENT_FILE_FK1" FOREIGN KEY ("BOARD_NUM")
	  REFERENCES "CLEVERNOTEADMIN"."BOARD" ("BOARD_NUM") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" ADD CONSTRAINT "BOARD_FK1" FOREIGN KEY ("TYPE_NUM")
	  REFERENCES "CLEVERNOTEADMIN"."BOARD_TYPE" ("TYPE_NUM") ENABLE;
  ALTER TABLE "CLEVERNOTEADMIN"."BOARD" ADD CONSTRAINT "BOARD_FK2" FOREIGN KEY ("USER_NUM")
	  REFERENCES "CLEVERNOTEADMIN"."APP_USER" ("USER_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."CATEGORY" ADD CONSTRAINT "CATEGORY_FK1" FOREIGN KEY ("OWNER_NUM")
	  REFERENCES "CLEVERNOTEADMIN"."APP_USER" ("USER_NUM") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTE
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."NOTE" ADD CONSTRAINT "NOTE_FK2" FOREIGN KEY ("CATEGORY_NUM")
	  REFERENCES "CLEVERNOTEADMIN"."CATEGORY" ("CATEGORY_NUM") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAGGING
--------------------------------------------------------

  ALTER TABLE "CLEVERNOTEADMIN"."TAGGING" ADD CONSTRAINT "TAGGING_FK2" FOREIGN KEY ("NOTE_NUM")
	  REFERENCES "CLEVERNOTEADMIN"."NOTE" ("NOTE_NUM") ENABLE;
  ALTER TABLE "CLEVERNOTEADMIN"."TAGGING" ADD CONSTRAINT "TAGGING_FK3" FOREIGN KEY ("TAG_NUM")
	  REFERENCES "CLEVERNOTEADMIN"."TAG" ("TAG_NUM") ENABLE;
