SELECT * FROM    ALL_CONSTRAINTS
WHERE    TABLE_NAME = 'CHALLENGE_RESULT';


SELECT A.TABLE_NAME, B.COLUMN_NAME, A.CONSTRAINT_NAME, A.CONSTRAINT_TYPE, A.SEARCH_CONDITION
FROM USER_CONSTRAINTS A, USER_CONS_COLUMNS B
WHERE A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
AND A.TABLE_NAME = 'CHALLENGE_RESULT'
AND A.CONSTRAINT_TYPE = 'P';


-- 출처: https://darong92.tistory.com/18 [다롱이의 공부장]
